### ISSUE TITLE
make it possible to log persistent congestion

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/qlog#100]
This would be *really* important for generating metrics.

Logically, it's a congestion event, but I'm not sure if it would probably make sense to add this as a state to the `congestion_state_updated` event, because once you declare persistent congestion, your congestion controller enters either slow start or congestion avoidance (not sure which one, haven't implemented persistent congestion yet), which are already `congestion_state_updated` events.

**Comment by rmarx** [comment]
So currently this is done using a trigger of "persistent_congestion" on the `congestion_state_updated` event (i.e., https://quiclog.github.io/internet-drafts/draft02/draft-marx-qlog-event-definitions-quic-h3.html#name-congestion_state_updated).

Reading your issue above, that seems like all that's needed? I know you have more experience with persistent_congestion at this point, so wondering if that is enough or we need something else?

**Comment by rmarx** [comment]
I'm unsure if this is still an issue given my comment above @marten-seemann?

**Comment by LPardue** [comment]
What's the status here. Close it?
