### ISSUE TITLE
QPACK: dynamic table entries are "inserted," not "added"

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/qlog#113]
The draft should use the QPACK terminology.

**Comment by rmarx** [comment]
So, I'm not entirely sure what to do here... I based myself mainly on this section, which does use "added"/"evicted": 
https://tools.ietf.org/html/draft-ietf-quic-qpack-16#section-3.2.2

However, I agree that in other places, "inserted" is used for the same/similar operations. I have changed it to "inserted" in qlog, as I trust @dtikhonov's good judgement, but wonder if this should be made consistent in the QPACK text? 

Similarly, several diagrams refer to the "dropping point" or "dropped count", which I -assume- is the same as "evicted" or "eviction index" etc. The "dropping point" is not mentioned in the running text anywhere in any case. Maybe that should also be made more consistent?

CC'ing @afrind on this. If needed, I can make issues in the quicwg repo for this.

**Comment by dtikhonov** [comment]
You're right: "inserted" is used nine times in the draft, while "added" is used six times.  My claim that entries are only "inserted," not "added," may have been incorrect!

**Comment by LPardue** [comment]
Closing since this is trivial, probably fixed, and any remainig inconsistencies can (and will) be raised later with ease.
