### ISSUE TITLE
Allow logging of TLS internals

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#120]
Depending on some TLS parameters, things might behave strangely on a QUIC level.

For example, TLS key shares can apparently use different "group types", e.g., p-256 or x25519 (this is somehow separate from the cipher it uses... I really need to brush up on my TLS understanding). The client chooses one of the groups that it thinks the server will support. If it doesn't the server will send an initial back, to which the client replies with another ClientHello using the correct group type, leading to a 2RTT QUIC handshake instead of 1RTT. An example can be seen in https://quic-tracker.info.ucl.ac.be/traces/20201101/2 (or if that's not longer available, a quic-tracker to mvfst connection setup, which seems to do this consistently).

This example above has already caught two separate researchers by surprise, and it should really be possible to expose this in qlog for easier debugging. 

In general, I think we can do with providing more options for logging TLS-level information, but for that I first need to understand the variables better (or find someone to propose the concrete things to surface in qlog for that).

**Comment by LPardue** [comment]
Applications can log what they like with their own events. Do we really need to say anything more?

**Comment by rmarx** [comment]
In one way, I would agree punting this to a broader TLS extension would be good.

In another, I really feel our current TLS capabilities of qlog are too limited to be of much use to debug TLS-specific aspects (e.g., it irks me we can't log extensions or ciphersuites properly, though I also hesitate to put this stuff in atm). 

Will mark this as needs discussion, as we need a plan for how deep we want TLS support to go imo.

**Comment by rmarx** [comment]
Seems like a duplicate of #59 (at least at this point...). Closing in favor of that one.
