### ISSUE TITLE
Add support for QUIC DATAGRAM and HTTP/3 DATAGRAM frames

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#124]
[QUIC DATAGRAM spec](https://tools.ietf.org/html/draft-ietf-quic-datagram-01)

[HTTP/3 DATAGRAM spec ](https://tools.ietf.org/html/draft-schinazi-quic-h3-datagram-05)

An interesting point was made about this by @lpardue, in that these frames are almost identical, with the H3 layer just adding a flow_id. 
For this, their implementation somewhat abstracts away the difference between these two, and their H3 code doesn't really have the concept of a DATAGRAM frame. 
For this, it would be interesting to have the flow_id field defined on the QUIC-level DATAGRAM as well, not just the HTTP/3 frame. 

To me, this feels a bit dirty, qlog not mirroring the specs to make implementation/logging easier. Still, it's something to consider.

An alternative is to implement this purely in the tooling. For example, qvis could just look for a flow_id field on the QUIC DATAGRAM frame, even though it's not defined in qlog proper. Alternatively, it could parse raw.data and extract the flow-id from that (which is worse...). 

This raises an overall point about the robustness of the tooling and whether we should mention something like this in the qlog texts.

**Comment by LPardue** [comment]
I think there is a place for the H3 DATAGRAM frame qlog object. The quiche implementation, at present, only provides transport layer logging but it would be logical to log an H3 layer frame if we supported it.

With what quiche has today, I would not implement flow_id logging for transport DATAGRAM. That would require me to do some layering violation and means the generic transport code suddenly becomes application aware. Its unfair to ask someone else to do the same violation I'm not willing to do and they might well reject it just as I have done. But implementations often have different incentives 😀

**Comment by LPardue** [comment]
There is some overlap here with discussion in the draft repo about whether a flow-id should go in the transport. One comment there described a TAPS concept where interface boundaries can accept a function that can be executed on behalf of the caller. Qvis could for instance by default just plot all datagrams as 1 "series", or plot multiple "series" based on a user supplied transform function such as varint(dgram_frame.bytes[])

**Comment by LPardue** [comment]
Based on other discussions, I think we should punt QUIC or HTTP/3 extensions to their own documents. So suggest close with no action on these documents.

**Comment by rmarx** [comment]
After discussion, it was decided to indeed handle these (and other, future) extensions in their own documents. 

For the DATAGRAM frames concretely, this has now been done at https://github.com/rmarx/draft-marx-quic-qlog-datagram. This is intended to be an example and testing ground of how to approach qlog extensibility in general. 

Small note: the original discussion on this issue regarding `flow_id` is now mute due to changes in how the DATAGRAM frames have been defined in their respective RFCs.
