### ISSUE TITLE
Remove implementation detail from PacketType enum

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#128]
At the moment, the PacketType enum has `onertt = "1RTT"` (and similar for 0RTT) because in most programming languages, enum keys cannot start with numerical characters. This has however led to some confusion in some cases, so it's probably best to leave out this implementation detail in the spec.

See also https://github.com/p-quic/pquic/issues/18#issuecomment-756005163

**Comment by lnicco** [comment]
@rmarx are you recommending just an editorial change to remove `= "1RTT"` and `= "0RTT"` or do you have something else in mind? 

I would see no issue in just using zerortt and onertt. Another option would be to add a prefix so that the first character is not a number, e.g. 

```
enum PacketType {
    initial,
    handshake,
    _0rtt,
    _1rtt,
    retry,
    version_negotiation,
    stateless_reset,
    unknown
}
```

**Comment by rmarx** [comment]
It would indeed just be an editorial change, but to be backwards compatible with existing qlog implementations, we shouldn't do `onertt` and `zerortt` but just 1RTT and 0RTT (as those are the actual serializations used atm).

The point here is that I feel we don't need to take into account the fact that most programming languages don't allow numericals as the first character in an enum; that should be an implementation detail.

So I'd propose:
```
enum PacketType {
    initial,
    handshake,
    0RTT,
    1RTT,
    retry,
    version_negotiation,
    stateless_reset,
    unknown
}
``
