### ISSUE TITLE
Formal definition of CommonFields seems to be missing

### ISSUE THREAD

**Issue by ptrd** [quicwg/qlog#130]
Section https://tools.ietf.org/html/draft-marx-qlog-main-schema-02#section-3.3 defines class Trace that has a field
`common_fields?: CommonFields`, 
however, the class CommonFields is not defined in the document.

**Comment by ptrd** [comment]
Hmm, 3.4.8 defines it. I missed it because i did a text search on "CommonFields", which occurs only once in the text.
Even though it is defined as a dictionary that can contains anything, personally, i would still like to see a class definition of CommonFields in the text. This could at least define the 4 default fields.

**Comment by rmarx** [comment]
This should now be fixed in the latest draft, at the bottom of the Section: https://datatracker.ietf.org/doc/html/draft-ietf-quic-qlog-main-schema-01#section-3.4.7.
