### ISSUE TITLE
Improve definition of event and data

### ISSUE THREAD

**Issue by ptrd** [quicwg/qlog#131]
As discussed on Slack, i find definition of event and data object a bit confusing. 
Some suggestions for improvement:
- https://tools.ietf.org/html/draft-marx-qlog-main-schema-02#section-3.4.3: TransportPacketSentEvent is not an event in the terminology of this document, but an example of data object; as such, i'd suggest to name it TransportPacketSentData
- it would help if the data serialization example in the same section would also show how the data object fits into the event (i.e. include the event in the example)
- https://tools.ietf.org/html/draft-marx-qlog-event-definitions-quic-h3-02#section-5: i'd suggest to also mention each subsubheading / event-type will define the data class that is referred to in main-schema
- why not use the more formal way of defining a data class used in the main-schema document (e.g. class TransportPacketSentData) in stead of the informal "Data" label this is now used in quic-schema? The latter confuses me, because it makes me wonder how it fits in the formal definition of event. Also, it would be helpful as one can find the QUIC example in main-schema (TransportPacketSentEvent) in the QUIC-document; currently this example cannot be found in the quic-doc, which is a bit confusing also as it states the example is taken from QUIC ;-)
- the definition (example) of TransportPacketSentEvent in main-schema does not match the definition in quic-doc  section 3.5.3; either make them equal or add a note in the main-schema document that it is only partial.

**Comment by LPardue** [comment]
Since this ticket was opened, we've switched to CDDL and tightened up our terminology usage around Events and Data. I think some of the original points have been addressed but it would be good to double check. 

One comment that might have hungover is 

> TransportPacketSentEvent is not an event in the terminology of this document, but an example of data object; as such, i'd suggest to name it TransportPacketSentData

This is now called simply `TransportPacketSent`, however it belongs to `QuicEvents`, which extends `$ProtocolEventBody`, which is defined in https://www.ietf.org/archive/id/draft-ietf-quic-qlog-main-schema-04.html#figure-15 as 

```
Event = {
    time: float64
    name: text
    data: $ProtocolEventBody

    ? time_format: TimeFormat

    ? protocol_type: ProtocolType
    ? group_id: GroupID

    ; events can contain any amount of custom fields
    * text => any
}
```

**Comment by LPardue** [comment]
To add a bit more. I don't really have much problem with an Event's `data` field containing an abstract notion of something called `QuicEvents` or similar. When it comes to concrete events in serialized form it'll all tend to look the same. However, if we really wanted to consistent with terminology, perhaps something to consider is

1. Rename `$ProtocolEventBody` to `$ProtovcolEventData` throughout
1. Recommend that extensions are names `NewProtocolEventData`
1. Rename our extensions
   * QuicEvents -> QuicEventData
   * HTTPEvents -> HTTPEventData
   * QPACKEvent -> QPACKEventData
