### ISSUE TITLE
Multipath support

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#134]
With the multipath conversation gaining traction in the QUIC wg, it's time to start thinking more seriously about adding (rough) multipath support to qlog and qvis to aid practical implementation efforts (e.g., see https://huitema.wordpress.com/2021/01/26/implementing-multipath-in-quic).

The simplest approach that I can see would be to associate a `path_id` with each qlog event:

```
Event definition without multipath:
class Event {
    time: number,
    name:string,
    data:any
}

Event definition with multipath:
class Event {
    time:number,
    name:string,
    path_id:number | string,
    data:any
}
```

This would allow users to log all events belonging to a single "connection" to differentiate per-path events without having to split them up in separate qlog Trace objects. Additionally, it prevents from having to overload the existing `group_id` field with an additional meaning.

However, the main problem I can see is that the `path_id` (which can be anything, preferably an opaque/obscured value) is not available everywhere in the code that wants to output a qlog event. For example, a congestion controller will wish to output the `recovery:metrics_updated` event, but might not necessarily have the `path_id` available in the code path where these metrics are calculated/available (e.g., if a congestion control method is re-used as-is between single-path and multi-path QUIC). Similar concerns exist for other events (e.g., ACK processing or event `packet_sent` if this is logged before the packet scheduler decides which path to take). 

While there are of course always solutions to this (e.g., pass the path_id as extra parameter/as global variable/put it on a stack/put it on a logging object reference/etc.) it is at this time unclear if this is an actual problem and if implementers would wish to add these patchwork "solutions" if required, just to get proper qlog output.

CC @huitema @mpiraux

**Comment by huitema** [comment]
I will try implement that and give you feedback. I think this is natural for QUIC level events, not so much for application level events.

**Comment by rmarx** [comment]
Excellent! Having implementation experience will help here, while example output traces will help get something into qvis. 

The `path_id` would indeed only be for transport-layer events. For application-layer events, I was thinking to either omit the `path_id` (and specify that events without path_id should be considered cross-path/valid for all paths/...) or give a special `path_id` value (e.g., "app"), though omitting it seems cleanest and most optimized.

**Comment by huitema** [comment]
I am finding a first difficulty: how does one define the path identifier? The uniflo ID in draft-deconinck and the DCID sequence number in draft-liu have very similar properties: they define flows in only one direction. But the numbers derived from the DCID are place holders. The "actual path" is defined by the addresses and ports from and to which packets are sent. The DCID maps to that when it is present, but what if is not? Today, a popular setup is for clients (but not servers) to use NULL connection IDs -- this minimizes overhead in the server-to-client direction. The solution that I presented in draft-huitema allows that; my implementation of draft-liu also allows it. But if there is no DCID in the packets sent from server to client, how shall I define the path-id?

For picoquic, I could use the DCID ID sequence number when the DCID is present, and an arbitrary "path number" when it is not. But doing that will not result in a good log, because if the choice is arbitrary the path-id in the client log may not match the path-id in the server log. We do want to be able to match events from client and server log, so we have to do something better. My take is the following:

* If the DCID is present, use the number associated with it.
* If the DCID is NULL, check whether there is a CID used in the reverse direction. If it is present, use the number associated with that CID.
* If the DCID is NULL in both direction, use the number 0.

Note that if solutions allow the use of NULL DCID, they will need to somehow provide a way to identify the paths -- if only because they need to ask the peer to "abandon path X" when they loose connectivity on that path, and they need an identifier for that. It is just that the proposals are not quite mature enough...

**Comment by rmarx** [comment]
That is some very useful feedback! 

I hadn't considered that we need to define a way to choose the `path_id` to make it possible to sync up client and server-side traces purely on `path_id`... I think your proposal makes sense, though we would have to specify concretely how to derive the `path_id` "number" from the connection ID (i.e., simply taking the first/last 8 bits or similar is simple enough, but might not be optimal considering privacy down the line (e.g., in setups where you don't even want to log the real CIDs)). 

An alternative approach would be to shift the client/server path correlation to the tools themselves (i.e., have them use knowledge about the Multipath extension and IP+port info to link `path_id`s), but that has similar privacy issues...

It seems like the final solution would indeed depend on the chosen Multipath design (e.g., if that always requires a DCID + seq nr or Uniflow ID, we can just use that). For now, we can probably make due with a simpler scheme like the one you propose to get implementation experience.

**Comment by nibanks** [comment]
Personally, I'd add a PathCreated event, that defines an arbitrary ID and all the parameters necessary to describe it. You might also want a PathUpdated event if you need to modify any of those parameters before the PathDestroyed event. For all other events that much represent "the path" they merely use the arbitrary ID.

We generally try to use this model for all event logging in MsQuic, though, much of the time, we use the object * for the ID for additional usefulness when live debugging.

**Comment by huitema** [comment]
@nibanks with arbitrary identifiers, how do you reconcile client log and server log?

**Comment by nibanks** [comment]
You obviously cannot just use the ID value. You must search for two paths with the same parameters and associate those path objects.

**Comment by rmarx** [comment]
That seems tantamount to the second option I described @nibanks, but the question then becomes: what are those parameters? IIUC those would mainly be IP+port info, which is not something a privacy-aware endpoint would want to include in their qlogs.

**Comment by nibanks** [comment]
If you're warry of PII, you simply include a hash of the information. Then your parser must understand both raw data format and hash format. If one side includes raw and the other a hash, then the parser converts raw to hash and does the comparison.

**Comment by rmarx** [comment]
So that is a more general question I'm struggling with wrt qlog privacy and whether hashing is enough. Conceptually, if the attacker is looking for a specific (set of) IP(s) or users, and the hashing function is known (which it has to be to correlate independent client-server logs), they could still derive if a trace was for a given IP/user or not by generating hashes for all IPs/users under consideration. 

I'm not at all sure if that's an actual concern in practice or even something that can be worked around (I need to do more reading on data anonymization). It's also a bit esoteric, as you'd only need to use that type of hashing if you know you want to cross-correlate logs (which you probably don't want to do in production?), otherwise you can just use internal opaque IDs. But that's a potential issue here imo, and one that could require a rework of the mechanism should we choose the hashing approach now and it is deemed too "dangerous" later. 

As I've said however, for now to allow us to make progress, I have no qualms choosing this type of approach to get experience. I also feel some generic path-related events are needed (e.g., path_created, path_updated, path_removed etc.) besides just the `path_id`.

**Comment by nibanks** [comment]
First off, I think the notion of privacy should be a separate Issue and not discussed here. Still, I don't think you're going to be able to completely solve this without exchanging a completely arbitrary value on the wire. If you want two independent parties to log the same thing, they have to agree on a mechanism to turn PII_DATA -> ANONYMIZED_DATA. So you have to standardize a mechanism to do that. If it's standardized then anyone who knows of a particular PII_DATA can convert it as well. The best you can do is have the method be key based, but that only helps if 1) both the client and server know the key and 2) the person you want to view the logs but not be able to correlate **not** know the key. I'm not sure how you'd achieve that.

**Comment by huitema** [comment]
Yes, the tools could rely on addresses and ports to match paths. But in the presence of NAT the values changes. You end up requiring heuristics.

As for going to anonymized data, there is a whole body of literature on the subject, and it is not easy to be both anonymous and useful. Plus there is an interesting problem of comparing hashes after NAT.

**Comment by huitema** [comment]
Another question regarding default values. What happens if there is path_id specified for some events, but not for others?

Asking that because I would like to not include a path_id in the qlog files if not using multipath. My preference would be using a default "path_id = 0" when the element is absent.

**Comment by rmarx** [comment]
As I mentioned above (https://github.com/quiclog/internet-drafts/issues/134#issuecomment-768970236), I indeed feel you should be able to omit `path_id` on events that do not require it and that a single trace can perfectly contain events with and without `path_id` set. 

I don't fully agree with the semantics of making an omission imply a default path_id value though, as e.g., HTTP/3 events will probably always lack a `path_id` as they belong to "all paths" concurrently. 

Put differently: there is a (subtle) difference between "omission = default value" and "omission = belongs to all paths", and I'd prefer the latter. This also holds up in the non-multipath case.

**Comment by huitema** [comment]
I have a bit of a situational argument. I have logging tests that simulate a connection, generate a log, and compare the log to the reference value. As I am implementing multipath log, I am running these monopaths tests and verifying that "nothing changed". The alternative would be to allow that something changes (allow path_id=0 here and there), and then check the result line by line to verify that the difference with the reference is as expected. Of course that's doable to. It is just way more time consuming...

**Comment by huitema** [comment]
I just realize that the syntax here implies qlog v2. That's going to take a bit longer than I initially thought...

**Comment by huitema** [comment]
OK, so I went ahead and updated the picoquic qlog code to add a path_id to the event header when multipath is being negotiated. Although conceptually simple, that changes a lot of code in a lot of places. The PR is at https://github.com/private-octopus/picoquic/pull/1124.

Here is an example of multipath log:
[multipath_qlog_ref.txt](https://github.com/quiclog/internet-drafts/files/5899304/multipath_qlog_ref.txt)

**Comment by huitema** [comment]
This is another example of qlog with multipath traffic: 
[simple_multipath_qlog_ref.txt](https://github.com/quiclog/internet-drafts/files/5938171/simple_multipath_qlog_ref.txt). This one uses the "simple multipath" option that I defined in my original draft, which uses a single packet number space. As you will see, the sequence displays well with qvis, although some visualisation of path-id would be nice. The congestion graph, on the other hand, is also wrong. Maybe less wrong than the previous multipath variant, but there really should be one graph per path for congestion window, bytes in flight, etc.

**Comment by LPardue** [comment]
To avoid scope creep, I think we need to punt as much of the multipath qlog work as possible on to another document. 

What are the minimal viable changes to the qlog specs, that need to happen now, in order to ensure future work on logging can succeed? If the CDDL supports extension of type by insertion of new fields, I might suspect the minimal changes could be zero.

**Comment by huitema** [comment]
Yes, I suppose we could defer to "qlog extensions for multipath, TBD". But having a path_id in the header to qualify the packet number would be very convenient.

**Comment by LPardue** [comment]
A single field sounds reasonable today. Let's hammer down on whether anyone objects to that.

**Comment by huitema** [comment]
The multipath specification uses path specific number spaces. In 1 RTT packets, path numbers are qualified by a packet-number-space identifier (a.k.a., path ID). This is set to the sequence number of the destination OID. My early observation was that this was really confusing for tools like QVIS, which would see the same packet number occurring multiple times. Yes, they could somehow parse the transport parameters and infer that they should be multipath aware, and then match the sequence number space with the sequence number of the OID. But that's quite a bit of work, and stating the path-ID would make that process much simpler.

The other frames that are path aware are the ACK frames, Path Abandon Frames, and Path Status frames. There is a special type of ACK frame for multipath, and the ACK-MP frames explicitly carry the path ID; the Status and Abandon frames also do. No need for anything else than "learn to parse these frames."

**Comment by rmarx** [comment]
Fixed by https://github.com/quicwg/qlog/pull/336
