### ISSUE TITLE
add a field to log the code version

### ISSUE THREAD

**Issue by marten-seemann** [quicwg/qlog#136]
With many iterations of my qlog implementation running in production now, it would be helpful if there was a way to tell which version of my code generated any particular qlog file (even better if qvis could display it somewhere).

I suggest adding an optional `code_version` to the `Trace` container. Implementations could fill this field with whatever they want. In quic-go, I'd probably use something like `quic-go $(git describe --long --dirty)`.

**Comment by marten-seemann** [comment]
A similar argument applies to architecture information. It would be useful to have a field to log OS / architecture / kernel information / compiler version.

**Comment by rmarx** [comment]
I agree this is useful information, but I'm not 100% sure it makes sense to standardize this, as I'd assume the handling of this field would depend on the company/deployment/tool and as you say, the contents can also differ wildly. Note that it's in my opinion perfectly acceptable to have qvis display a field that isn't defined in the qlog docs as such (i.e., qvis is broader than qlog). 

If we do want to include this type of thing in qlog proper, I'd propose putting it beneath the existing `configuration` field, or add a new `environment` field.

**Comment by marten-seemann** [comment]
> Note that it's in my opinion perfectly acceptable to have qvis display a field that isn't defined in the qlog docs as such

Are you suggesting that qvis defines additional fields / events? That's an interesting idea.
In this case though, I'd argue that `environment` (which is a lot better name than the `code_version` I suggested) is something that would be a useful thing to display for a variety of tools, so it would probably make sense to define it here.

**Comment by rmarx** [comment]
So, I remain of the opinion that it would not make much sense to standardize this (whether it's Configuration, Summary, Environment or a combination thereof). The proposed new field in #208 as simply a generic text value reinforces that opinion. 

However, if we do want to do this, I'd propose to just merge all of this into a single field of a generic object type, i.e.,:

```
BikesheddedTypeName = {
    * text => any
}
```

Where people can go crazy adding `configuration`, `environment`, etc. members as they see fit. This feels more flexible than having a `text` field. 

Finally, #208 only adds this to the Trace object, not TraceSeq. Any chosen solution should be enforced on both trace types.

**Comment by rmarx** [comment]
Discussed on call. Decided to close this and associated PR with no action and keep the `configuration` field for this purpose.
