### ISSUE TITLE
Make protocol_type more well defined

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#146]
Currently, `protocol_type` is a single string which typically has the value "QUIC_HTTP3". 

However, this doesn't particularly scale to aggregated logs down the line (e.g., in #139 we can have a plethora of different protocols represented), and it isn't clear how to define new strings for new protocol types (e.g., is it TCP_HTTP2 or TCP_TLS_HTTP2 and in that case, why isn't it QUIC_TLS_HTTP3? etc.)

One direct solution might be to make the field an array of individual values (i.e., `protocol_type = ["QUIC", "HTTP3"]`), but that potentially adds additional overhead if the field is logged for each event individually. 

Another option would be to prefix event names with the protocol (e.g., `transport:packet_sent` becomes `quic:transport:packet_sent`) but that reduces the future potential to re-use events across protocols (not a big deal for QUIC vs TCP probably, but higher level logic events (say, `recovery:metrics_updated`) could suffer). 

This is somewhat tied to #85, as some events will be implicitly tied to a particular protocol anyway.

**Comment by nibanks** [comment]
Personally, I think events **should** be tied to protocol, and "sharing" them should not be a goal. IMO that's going to make things harder and more confusing to interpret, especially if you end up having both protocols in the same log. For Windows, we regularly use well-defined events and they are always specific to a particular component. Even if things might look similar now, that doesn't mean they would stay that way in the future. Forcing things to be the same would then limit the development of the one that wants to evolve.

**Comment by nibanks** [comment]
And one more data point for you, we generally follow a pattern for events to be named something along the line of <Component/Protocol><Object/Qualifier><Action>, such as `QuicConnVersionSet` and `QuicStreamCreated`. It allows for events to be globally unique and descriptive enough that you don't need too much follow up to explain what it is doing.

**Comment by rmarx** [comment]
This also has a potential impact on how we define the high-level `name` field vs the separate `category` and `event/type` fields, as tracked in #150.

**Comment by LPardue** [comment]
Closing this as done per my previous comment.
