### ISSUE TITLE
Add ability to log CPU/threading info

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#152]
In msquic, events all contain the current CPU ID, Process ID and Thread ID (https://github.com/microsoft/msquic/blob/main/src/plugins/wpa/DataModel/QuicEvent.cs), which allows them to do advanced debugging of threading and CPU allocation issues (https://github.com/microsoft/msquic/blob/main/docs/TSG.md#diagnosing-rss-issues).

It would potentially be interesting to have this type of metadata well-defined in qlog as well.

CC @nibanks

**Comment by nibanks** [comment]
Here's an example scenario where having CPU information per event is key to diagnosing issues: https://github.com/microsoft/msquic/blob/main/docs/TSG.md#diagnosing-rss-issues

**Comment by rmarx** [comment]
At this point, given that we are currently trying to end up with as few "standard" qlog events as possible, I wonder if it would make sense to keep this in.

It's always possible to add custom fields to indicate this information if needed for a given implementation. Additionally, I'm wondering if it would make sense to log this for each event in qlog instead of have separate events when a connection moves to a new CPU (as we already do that type of logic for other things, like we don't log spinbit in each packet_header but rather have a separate `spin_bit_updated` event). 

Specifically: I propose not doing this in qlog proper at this time.

**Comment by nibanks** [comment]
If this was supported, it would have to be per-event. When you have multiple threads firing off events in parallel, any/every thread may be generating an event at any time, even for the same connection. For instance:

Thread A: Queues a send on connection X, stream Y.
Thread B: Queues a send on connection X, stream Z.
Thread C: Processes connection X (sending and receiving data for streams Y & Z).

One thing to note, WPA **requires** thread and cpu/processor to be supplied for every event.

Also, as far as deciding if this is necessary, per-thread/processor scheduling is personally one of the main reasons I need tools for processing logs, and not just look at the raw text. I would find it very surprising if other server deployments don't also have similar experiences.

Personally, I'd prefer to at least define this in the spec, but possibly make it optional. If we want tools to be able to generically consume these fields, they can't be custom.

**Comment by LPardue** [comment]
The qlog direction to log wire events is fine for me. 

But it seems @nibanks is really discussing the kind of foundation event meta-data that might get logged, and why it is useful. I tend to agree. 

There's a benefit to considering this information in qlog, we can provide guidance about the data fields as part of security and privacy analysis. For instance, low-level information is useful for local developer analysis but might be too sensitive to share by default.

What would a common platform-independent schema for CPU/thread look like? Is there anything qlog can borrow from?

**Comment by nibanks** [comment]
FYI, [here](https://github.com/microsoft/msquic/blob/main/src/plugins/trace/dll/DataModel/QuicEvent.cs#L187) is the base (C#) object for events in the WPA event processing code. Generically, every event has at least an ID, timestamp, processor, thread ID, process ID and event-specific payload.

**Comment by LPardue** [comment]
It really does seem like endpoint-local data just like the timestamp. I can see cases where all of those could be useful, so optional fields sounds fine to me.

If all the info is needed to make sense, I might be tempted to define it as a single tuple rather than individual fields e.g. `hw_info: {processor_id: uint32, process_id: uint32, thread_id: uint32}`

**Comment by nibanks** [comment]
@LPardue that works for me.

**Comment by rmarx** [comment]
I think I can now better grasp the benefits of doing this within the context of qlog, so thanks for the additional discussion.

We can bikeshed the exact form this should take. I for example would suggest not putting this as a property of the `data` field (part of the payload) but rather as a top-level field (at the same level as timestamp, name and data itself). 

This would be something defined in the main schema document, as it's usable across protocols. 

Assigning to @lnicco so he can get his hands dirty with adding something new :)
