### ISSUE TITLE
What is the media-type?

### ISSUE THREAD

**Issue by kazuho** [quicwg/qlog#158]
What is the [media-type](https://www.iana.org/assignments/media-types/media-types.xhtml) of the qlog files?

**Comment by rmarx** [comment]
This is currently not yet defined...

At first instinct, I'd say `application/qlog+json`, but I'm not sure how we'd indicate the difference between normal JSON and newline-delimited JSON (if we even decide to keep that). Maybe `application/qlog+ndjson` and then something like `application/qlog+cbor` down the line?

Not sure how easy/difficult that would be to deal with for qlog tooling / how media-type parsers typically deal with this type of thing.

**Comment by kazuho** [comment]
Thank you for the response.

For context, the reason I asked is because h2o has a well-known URI for serving traces, see https://mailarchive.ietf.org/arch/msg/quic/VHyaEIHxYylfg5NAKBxccycqnvc/.

At the moment, we use a custom ndjson format, but if we are to use qlog, there has to be a media-type.

**Comment by LPardue** [comment]
Fixed as far as I can tell, closing.
