### ISSUE TITLE
Inconsistencies when talking about the "trigger" field

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#166]
Across the qlog docs, the text seems inconsistent when it mentions the "trigger" field, and whether that is a property of Event of Event:Data. For example

```
For each event type, its importance and data definition is laid out, often accompanied by possible values for the optional "trigger" field.
```

IIUC, "trigger" is supposed to be only defined for Event:Data that cares to define it. It would help to sweep the docs to ensure consistency in this area.

**Comment by rmarx** [comment]
Current plan is to address this by including triggers directly in the event data definition instead of separately.

See https://github.com/quiclog/qlog/tree/master/CDDL/schema#triggers.

**Comment by LPardue** [comment]
over taken by other editorial changes, so closing.
