### ISSUE TITLE
Allow multiple packet_numbers in frames_processed

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#168]
Currently, `frames_processed` only allows indicating a single packet_number.

However, discussion in #163 has shown that you might want to aggregate frames across multiple packets for some use cases, so it makes sense to make this into an `Array<uint64>` instead.

**Comment by incfex** [comment]
About this structure
```
frames_processed : 
{
       frames:Array<QuicFrame>,
       packet_numbers?:Array<uint64>
}
```
How do we log the packet_numbers when we have multiple frames in one packet? My suggestion is we log them one to one.

Example (suppose fr1 and fr2 are in the same packet):
```
{
       frames:[fr1, fr2, fr3, fr4],
       packet_number:[1, 1, 2, 3]
}
```

This way we don't have to do any search when the packets arrive out of order.

**Comment by rmarx** [comment]
Good point and your suggestion seems sensible :)
