### ISSUE TITLE
h3 parameters: s/max_header_list_size/max_field_section_size

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#175]
The name of the setting was changed in draft 28

**Comment by rmarx** [comment]
Thanks Lucas, good catch!

I'm trying to track all of these minor changes in #174 and we plan to do them in bulk when going over all the definitions when switching them to CDDL. 

Feel free to report other similar changes, as individual issues with a reference to #174 or as comments on that issue directly.
