### ISSUE TITLE
Figures contain lines that are too long

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#179]
An editorial issue, but one that is good to get solved with a general approach that will avoid nit blocking eventual publication.

Here's an example of the nits from the main schema draft

```
  Checking nits according to https://www.ietf.org/id-info/checklist :
  ----------------------------------------------------------------------------

  ** There are 30 instances of too long lines in the document, the longest
     one being 329 characters in excess of 72.
```

We had a similar problem in the Digest draft, some things like hashes or JSON objects are too long. Here's what we did https://httpwg.org/http-extensions/draft-ietf-httpbis-digest-headers.html#appendix-C

> Some examples include JSON objects in the content. For presentation purposes, objects that fit completely within the line-length limits are presented on a single line using compact notation with no leading space. Objects that would exceed line-length limits are presented across multiple lines (one line per key-value pair) with 2 spaced of leading indentation.

**Comment by rmarx** [comment]
We plan to tackle this in the move to CDDL.

**Comment by rmarx** [comment]
Should be fixed in main-schema-02 and h3/quic-events-01 (I'm no longer getting any ID-nits errors on the documents).
