### ISSUE TITLE
QUIC relies on ApplicationError, which is defined only for HTTP/3

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#183]
I recently refactored quiche's qlog implementation to split events into their own modules for general, QUIC and HTTP/3. In follow up work, I realised our implementation of the ConnectionClose frame was stale and I attempted to fix it up here https://github.com/cloudflare/quiche/pull/1079/commits/866292b923ce2fe236fcced0a641607e3be60bec. The definition of that frame at the time of writing is below, and a far as I can tell, `ApplicationError` is only defined in the HTTP/3 spec.

```
class ConnectionCloseFrame{
    frame_type:string = "connection_close";

    error_space?:ErrorSpace;
    error_code?:TransportError | ApplicationError | uint32;
    raw_error_code?:uint32;
    reason?:string;

    trigger_frame_type?:uint64 | string; // For known frame types, the appropriate "frame_type" string. For unknown frame types, the hex encoded identifier value
}
```

In code review, it was highlighted that including an HTTP/3 enumeration in my QUIC module code is a bit strange (feels like a priority inversion). Also, it doesn't seem to scale to support other applications. I think perhaps what is needed is for there to be an "externalised" ApplicationError union type like `type ApplicationError = Http3Error | NewStuff`, or maybe even that doesn't work well for supporting new application protocols...

**Comment by kazuho** [comment]
Is there a reason to expose the semantics of application protocol in at QUIC level?

IMO, trying to expose HTTP3Error at QUIC level is no less strange than asking to decode the HTTP headers being transported by the STREAM frames, or the HTTP/3 stream type.

I would hope that the QUIC-level traces would just show the error codes in numbers, much like they just log the stream IDs / bytes being exchanged.

**Comment by LPardue** [comment]
That would work too. We could invent new application error event types that sit in H3, and then correlate to QUIC frames bearing the integer value

**Comment by rmarx** [comment]
Good catch, and I feel this is primarily an oversight of mine in forgetting to change this when splitting up QUIC and H3 events...

I agree it doesn't make sense to have the ApplicationError class in the QUIC events doc and that we should revert to just having `string | uint32` there, with some extra guidance that application-specific qlog docs should make that more explicit (e.g., with the ApplicationError enum that maps to strings in the H3 doc). 

Having separate error events at the H3 layer is imo perpendicular to this, but certainly also not a bad idea.

**Comment by LPardue** [comment]
String | uint32 works for me and means we likely never have to revisit this space

**Comment by rmarx** [comment]
With CDDL, we will be able to do better than `string | uint32` as it can define extension points (called sockets/plugs in CDDL) with `$`. 

Will probably look something like:
```
# in QUIC document:
$ApplicationErrorType

# in HTTP/3 document:
$ApplicationErrorType \= H3ApplicationError

# in future WebTransport document
$ApplicationErrorType \= WTApplicationError

```

**Comment by rmarx** [comment]
This was added in h3-events-01 as such:

```
HTTPApplicationError =  "http_no_error" /
                        "http_general_protocol_error" /
                        "http_internal_error" /
                        "http_stream_creation_error" /
                        "http_closed_critical_stream" /
                        "http_frame_unexpected" /
                        "http_frame_error" /
                        "http_excessive_load" /
                        "http_id_error" /
                        "http_settings_error" /
                        "http_missing_settings" /
                        "http_request_rejected" /
                        "http_request_cancelled" /
                        "http_request_incomplete" /
                        "http_early_response" /
                        "http_connect_error" /
                        "http_version_fallback"

; ensure HTTP errors are properly validate in QUIC events as well
; e.g., QUIC's ConnectionClose Frame
$ApplicationError /= HTTPApplicationError
```

With the quic-events-01 properly exposing the `$ApplicationError` CDDL extension socket.
