### ISSUE TITLE
Add a way to indicate sent-but-unacked data

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#186]
Once data for a stream is sent in a packet, it has to remain in some form of retransmission buffer (either a separate buffer or as ranges in the main stream buffer or ...) until the data is ACKed as received, only then can it be discarded completely. 

At this time, there is no way to track how much sent-but-unacked data is outstanding for a given stream. 

The most organic way to do this seems to be to add a new target to the `data_moved` event. We currently have `"user","application","transport","network"`, where we might regard "network" as being "sent but unacked", but then we still lack a "discarded" state. 

Bikeshedding is possible on the name: "discarded", "resolved", "acknowledged", ... as conceptually we could even replace the "user" target with this one as well, and saying that indicates the data has left the "network protocol stack" (either on the sender or receiver side), terming it as "handled"/"resolved" would make sense there.

cc @LPardue

**Comment by rmarx** [comment]
This seems related (at least a bit) to https://github.com/quicwg/qlog/pull/396.

I'm not sure we still want to go down this road (also don't remember what first triggered opening this issue). 
As it is, it seems like this is something that can be done on a per-implementation basis if needed (using the mechanism I described above), which probably makes most sense since this is mostly for debugging internal memory management, which is unlikely to be the same across stacks (and unlikely to be able to properly use generalized tooling). 

Proposal: close without action. What do you think @LPardue ?

**Comment by rmarx** [comment]
Some final thoughts on this @LPardue or I'll close with no action :)

**Comment by LPardue** [comment]
I checked the quiche implementation again, we actually extend `$DataLocation` with a `dropped` value. When processing acks, we'll trigger a stream_data_moved event from `transport` to `dropped`.

I don't currently actively use this in my tooling but I could (and now I've been reminded it exists, I'm excitied). 

Given that DataLocation is extensible , I have a custom solution that works for my needs. I'm not hearing any other interest in this right now. It would be easy enough for someone to standardize in future if they wanted.

Propose to close with no action.
