### ISSUE TITLE
Remove Summary and Configuration

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#187]
We currently have the `summary` (in QlogFile) and `configuration` (in Trace) fields.

These fields made sense when qlog was viewed as a file format that would primarily be used to aggregate multiple traces into a single file, which would then be transferable between different tools (e.g., in research settings). 

However, with most implementations shifting to streaming logging (1 trace per file) and no tools emerging that rely on interoperability via the `summary` and `configuration` fields, I feel it makes sense to just remove them from the spec. This is further motivated by the fact that Summary is defined as just a generic JSON object and Configuration only has 2 recommended fields, 1 of which is `original_uris`, which again only makes sense if we see this as a grouping format. 

See also #184, cc @LPardue

**Comment by LPardue** [comment]
+1 to simplicity. 

It seems like it's going to be straightforward for anyone to add such fields in future if they really need them. Being judicious with we things we include in the base spec will make it more straightforward for people to focus on the valuable items.
