### ISSUE TITLE
Scope of draft-ietf-quic-qlog-main-schema

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#197]
Editorial work on draft-ietf-quic-qlog-main-schema has been a lower priority than the design work. That's fine. But as we look ahead, we should think a bit about what the scope or pitch of the document is. Right now the document is titled "Main logging schema for qlog" and the abstract says:

> This document describes a high-level schema for a standardized logging format called qlog. This format allows easy sharing of data and the creation of reusable visualization and debugging tools. The high-level schema in this document is intended to be protocol-agnostic. Separate documents specify how the format should be used for specific protocol data. The schema is also format-agnostic, and can be represented in for example JSON, csv or protobuf.

In reality the document speaks to both the schema and all of the ways that applications might use qlog.Editorial questions to ask for this draft are:

Does it need to do both of these things in the same document?
Is there stale text that can be deleted to improve focus?
More drastically, is there any benefit in splitting the document into schema and usage drafts?

**Comment by rmarx** [comment]
I agree with the general sentiment here, and I would indeed go a step further in suggesting we should remove some parts (mainly 6.3 the "other optimized formatting options", and some smaller stuff here and there).

Other than that, I feel that especially section Section 7 ("Methods of a access and generation") and 8 ("Tooling requirements") might be split up into a separate document. A long time ago I discussed this with @britram and he seemed to feel that sort of thing belonged more in the ops area (though we might want to keep it in quic wg just for consistency, idk). 

Is that the split you had in mind @LPardue, or would you group things differently?

**Comment by LPardue** [comment]
Yeah something along those lines feels right. Thanks. Not urgent to do it yet but good tp start thinking ahead.

**Comment by LPardue** [comment]
I'm feeling pessimistic about creating any new documents. Editorial improvements to the adopted drafts can be tracked in other issues - closing this issue.
