### ISSUE TITLE
State document structure more accurately

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#220]
In qlog and h3 event definitions, there's a pattern in section 2 to say "each subsecion and subsubsection defines xyz". However, the definitions are actually in section 3. Suggest that we make this more accurate.

**Comment by rmarx** [comment]
As discussed in the editor's meeting yesterday, it should indeed be made clearer how (sub)section names map to event names etc. without it being (purely) implicit in the document structure.

I think your existing PRs #226 and #237 go a ways towards that @LPardue. 

I would maybe argue we should also either add an explicit entry/comment for each of the events showing its full serialized name (e.g., the `version_information` Section in quic-events would have an explicit indication saying it's `name` field should be `transport:version_information`). Though maybe that's overkill if we list it in a "TOC" and make the text mentioned in this issue clearer ?

**Comment by LPardue** [comment]
I think things are ok in editors copy. Closing and will make new issues for more specific concerns,
