### ISSUE TITLE
Restating CDDL syntax is not necessarily a good thing

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#230]
In the main schema document, there's a a chunk of text that says:

> The main general CDDL syntax conventions in this document a reader should be aware of for easy reading comprehension are:
>
> // list of things

The danger with restating things like this is that there is some subtle problem or incompatibility with the canonical CDDL source citation. I appreciate the QUIC WG might not be familiar with this syntax, so it's handy. But the long-term problems a more insidious. Consider replacing it with deep links to CDDL syntax, or sticking it behind a note that it will be removed prior to publication.

**Comment by rmarx** [comment]
Yes, the intent is to remove this prior to publication. It's just there to make early adoption easier for now. 

Will look up how to properly add such a note (not sure if there's something default in the kramdown for that) and add it.
