### ISSUE TITLE
Gratuitous use of "we"

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#233]
Across the qlog docs, there's ~50 instances of the word "we", compared to 1 in RFC 9000.

We (pun intended) need to rephrase the specification to move away from that style. 

For example,

> To aid in this decision making, we recommend that each event SHOULD have an
"importance indicator" with one of three values, in decreasing order of importance
and expected usage:

can be rewritten as

> To aid in this decision making, each event SHOULD have an
"importance indicator" with one of three values, in decreasing order of importance
and expected usage:

Or, this example

> ; but for many protocol fields we want to be more restrictive
; and explicit

can be rewritten as

> but many qlog fields benefit from more restrictive integer types

PS. a lot of these are in text that might be due to the cutting room floor anyway. But tidying up the style sooner everywhere is a faster way to resolve the problem while we think about what to keep or cut.

**Comment by rmarx** [comment]
Yes, I of course fully agree. A lot of the prose is written in faux academic paper style and should be updated to RFC-style. I could definitely use some pointers on how to best approach that, and the examples above help with that!
