### ISSUE TITLE
HTTPStreamType: why do we have an `old` and a `new` fields? .

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#236]
Sorry if that's a stupid question, but why do we have an `old` and a `new` field here? I thought you can only set it once.

_Originally posted by @marten-seemann in https://github.com/quicwg/qlog/pull/227#pullrequestreview-1111456120_

**Comment by rmarx** [comment]
This is a fair question.

This is most likely a copy-paste from one of the `*Updated` events (can't find evidence that this was once called StreamTypeUpdated though...)

For updates this makes sense, but if the StreamType is only ever set once after becoming known, it would be better to change the definition to e.g., (note, `raw_stream_type` is from #227) :

```
HTTPStreamTypeSet = {
    ? owner: Owner
    stream_id: uint64

    stream_type: HTTPStreamType
    ? raw_stream_type: uint64

    ; only when stream_type === "push"
    ? associated_push_id: uint64
}
```
