### ISSUE TITLE
Check that we can log version mismatch errors appropriately

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#241]
As noted in https://github.com/quicwg/qlog/pull/138#issuecomment-801995115, version mismatch problems causing a connection close are logged in 3 ways currently:

1. with a `version_mismatch` trigger value in `connection_closed`
2. by logging the on the wire versions in `packet_sent` and `packet_received` `.supported_versions`
3. by emitting a separate `version_information` event grouping both external and internal (see below)

```
TransportVersionInformation = {
    ? server_versions: [+ QuicVersion]
    ? client_versions: [+ QuicVersion]
    ? chosen_version: QuicVersion
}
```

This feels clunky, but probably gets the job done, with 1 proposed change:
Currently QuicVersion is defined as `: hexstring` and I would define it as `: hexstring / "none"` to support the mismatch case explicitly in that event as well (currently you'd omit the `chosen_version` field to signal the same). 

Another change we could do is to add `? supported_versions: [+ QuicVersion]` to the `server_listening` event to make it more explicit which versions a server supports at startup (currently no real way to indicate that). Not sure this is crucial though.

-------------------

One of the main points however is that I'm not sure this:

1. allows logging of all the possible flows with the [VersionNegotiation extension ](https://www.ietf.org/archive/id/draft-ietf-quic-version-negotiation-10.html). Maybe someone who's implemented that logic can give some insight? CC @huitema
 
2. should even be an issue for the qlog documents (as we're [leaning towards](https://github.com/quicwg/qlog/issues/124#issuecomment-1240048715) having separate qlog documents for separate QUIC features/extensions). CC @LPardue

**Comment by LPardue** [comment]
We closed the PR that was linked to this (https://github.com/quicwg/qlog/pull/138) so can we just close the issue?

**Comment by rmarx** [comment]
Looking into it a bit more, I think the canonical way for this can (should) indeed just be:

1. Log `TransportVersionInformation` **without** the `chosen_version` field set
2. Log `connection_closed` with a trigger value of `version_mismatch`

Given that we're not explicitly supporting https://datatracker.ietf.org/doc/rfc9368/ and that this can easily be added by adding a new transport parameter (which is now perfectly possible with #417), I will indeed close with no action now.
