### ISSUE TITLE
Security and Privacy: mentioning user consent and preferences

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#260]
The version of the [Security and Privacy Considerations in main-schema-draft-04](https://www.ietf.org/archive/id/draft-ietf-quic-qlog-main-schema-04.html#name-security-and-privacy-consid) contains a discussion on end-user preference and privacy control systems. This was included because a) I found it an important aspect to discuss and b) it mirrors the approach in [RFC6973](https://www.rfc-editor.org/rfc/rfc6973), which I've used initially as a baseline for the section. 

As @martinthomson noted in [an initial review of that paragraph](https://github.com/quicwg/qlog/pull/252#discussion_r1002779120), we should be quite careful about the terminology here and the recommendations we make. For the text in -04 I already removed direct mentions of things like the GDPR; it's likely other changes are needed to get this text into proper shape. 

Related to #259.

**Comment by LPardue** [comment]
The SECDIR did an early review and did not note any concerns. Closing this issue for now since its easy enough to revist later on.
