### ISSUE TITLE
Split up HTTP/3 and QPACK into separate documents

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#262]
Currently, H3 and QPACK events are in the same document. However, they are separate RFCs and (relatively) separate concepts as well. 

For other related documents, such as RFC9218, we would have a separate qlog document anyway, instead of integrating it into the same doc. 

Finally, editorially it also makes sense to be consistent with the QUIC events doc in terms of structure (now, the H3/QPACK doc already seems like 2 docs appended together in an ad-hoc fashion). 

However, arguments can of course also be made to just keep them together as they are somewhat related and we already have 3 base qlog documents without the split.

**Comment by LPardue** [comment]
I support splitting the documents up. The documents will be short and dry, but that seems fine for specifications defining schema based on other RFCs.
