### ISSUE TITLE
Would an is_ack_eliciting flag be helpful for packet_sent events?

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#275]
This came up in discussion I had with someone about calculating timing between packets that require acks and the packets that ack them. Not all packets are ack-eliciting and although it can be determined by looking at the frames inside a packet, that's potentially a bit labourious. 

There's prior art here, packet_sent already includes `is_mtu_probe_packet: bool .default false`, which seems like a similar use case.

**Comment by marten-seemann** [comment]
Not sure if `is_mtu_probe_packet` can be considered prior art. There's no definitive way to tell that a packet is a MTU probe packet without this flag (you can only have heuristics, checking if this packet is larger than the packets sent so far).

Also, `is_mtu_probe_packet` would only be set on a very small number of packets per connection (O(1)), whereas `is_ack_eliciting` would be set on O(N) packets.

**Comment by LPardue** [comment]
Fair point. 

I was also thinking that extension frames that are not eliciting and are not supported by tools would also cause those tools to draw the wrong conclusions.

If we flipped it and had an optional non-ack-eliciting field, I'd expect the impact to be lessened but still maybe too much for some people to bear.

**Comment by LPardue** [comment]
Given that we're adding things like ack frequency to make ack rates more flexible, I don't think such a field has tremendous value and I'm not hearing anyone else ask. Closing now. Maybe someone wants to revist this as part of future work in a new document.
