### ISSUE TITLE
Stop HTTP/3 events from squatting on the HTTP namespace

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#286]
Not all HTTPs are the same. I've just learned by meddling with netlogs that HTTP/2 and HTTP/3 might be quite similar but have subtle and annoying differences when it comes to logging. 

We have 

```
http:parameters_set 	Base 	Section 4.1
http:parameters_restored 	Base 	Section 4.2
http:stream_type_set 	Base 	Section 4.3
http:frame_created 	Core 	Section 4.4
http:frame_parsed 	Core 	Section 4.5
http:push_resolved 	Extra 	Section 4.6
```
and the event definitions themselves use `HTTP` as a prefix.

I'd suggest we just rename these to use `h3` and `http` respectively.

**Comment by rmarx** [comment]
I think this is a bigger issue than just HTTP/3... for QUIC we're currently using `transport`, but as I've also noticed e.g., TCP does not map nicely to the QUIC events. So potentially worth to discuss changing `transport` to `quic` as well (and what to do with the `datagram*` and TLS-related events then ;)

**Comment by LPardue** [comment]
Sure, but those are separate issues with their own considerations to make. 

The HTTP case is a lot more cut and dry to me. So I'd go ahead and fix it now via my PR.

**Comment by rmarx** [comment]
Discussed on call: general principle is ok. Create new issue to track `transport` changes.
