### ISSUE TITLE
HTTP header values (and possibly names also) should be optional

### ISSUE THREAD

**Issue by kazuho** [quicwg/qlog#295]
At the moment, the definition says that the value is mandatory.
```
HTTPField = {
    name: text
    value: text
}
```

However there are cases where the we do not want to log header values (consider a Cookie header).

**Comment by LPardue** [comment]
Yes, I think we should make the value optional and add some guidance in the security and privacy section specifically for header values

**Comment by LPardue** [comment]
Oh the main schema already has HTTP field value consideration described in https://quicwg.org/qlog/draft-ietf-quic-qlog-main-schema.html#section-9-4.7, so all we need to do is change the schema

**Comment by LPardue** [comment]
in #296 we merged a change to make the value optional.

I just realized that this issue said `(and possibly names also) should be optional`. @kazuho the HTTP field is only ever used in a list, so its' possible to omit entirely if you want to skip it. I'm not seeing a strong use case for endpoints to want to log:

1. a `value` but *not* the `name` of the HTTP field.  
2. A HTTPField list entry that omits both `name` and `value`

@kazuho my inclination is to close this issue not that `value` is optional, please let us know if you object.

**Comment by LPardue** [comment]
Hearing no objection, closing.
