### ISSUE TITLE
Is the .well-known address really necessary?

### ISSUE THREAD

**Issue by LPardue** [quicwg/qlog#313]
The main schema defines a means for clients to download generated qlogs by accessing them at a well-known address.  It hints that this is via HTTP but doesn't mandate that or provide more details about the expected HTTP interaction.

I'm curious how many people actually support this. The spec itself says that `qlog implementers SHOULD NOT enable this .well-known endpoint in typical production settings`, anyone that follows that advice will not. If we axpect this to be more of a debugging methodology, that might suggest that sharing the location (e.g. URI or something else) using out-of-band mechanisms would be just as managable. 

The proposal is also one sided. There is no capability defined for a client to submit its own logs for a server to later analyse. Not sure if that's a real problem but it is a constraint someone might question later in the process.

Since the .well-known access does not run in the "hot path" of event logging, it would seem fine to extract this and punt it to some follow on work.

**Comment by lnicco** [comment]
+1 
it seems to be more useful for interop-like tests than for production use cases, therefore I am not sure it necessarily belongs in the RFC

**Comment by rmarx** [comment]
Agreed during call: remove this from text. If needed later, will be separate document.
