### ISSUE TITLE
Improve connectivity:connection_closed

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#366]
As reported by @hlandau on the mailing list:

connectivity:connection_closed:

  This is missing the frame type field in the QUIC CONNECTION_CLOSE
  frame which is rather useful information.

  connection_code can be a string or a uint32, but QUIC uses a variable
  length integer here and thus this can be up to 62 bits. Same for the
  application_code.

  It is up to the decoder to infer by presence of connection_code or
  application_code to infer whether this was an application or transport
  CONNECTION_CLOSE. But this requires it to log such a value. It would
  be nice if this can be communicated without necessarily knowing the
  actual value. Consider either adding a field to distinguish between
  transport and app errors or replacing the "error" field of "trigger"
  with "app_error" and "transport_error".

**Comment by LPardue** [comment]
As suggested, it think it makes sense to udate this even to more closely resemble the CONNECTION_CLOSE frame structure e.g. have error_code and error_space fields

**Comment by LPardue** [comment]
I created #384 to address the frame type trigger field.

On re-reading the issue I realised I mininterpreted the request about not knowing an error code. If an endpoint doesn't know the specific error code, the trigger field allows to articulate tranport or app errors via the existing values.

**Comment by LPardue** [comment]
Closing as we think this can already be handled by other means
