### ISSUE TITLE
Clarify value of packets_acked:packet_number_space

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#372]
As reported by @hlandau on the mailing list:

quic:packet_acked:

  `PacketNumberSpace.application_data`, as this is by far the most prevalent packet
  number space a typical QUIC connection will use.

  Editorial note: The usage of the . notation
  `PacketNumberSpace.application_data` seems slightly novel here. Just
  write "application_data"?

**Comment by rmarx** [comment]
The goal here is not to have the string "PacketNumberSpace.application_data" literally as the value, but rather the value of that CDDL definition in the `PacketNumberSpace` struct definition lower in the document:

```
~~~ cddl
PacketNumberSpace = "initial" /
                    "handshake" /
                    "application_data"
~~~
{: #packetnumberspace-def title="PacketNumberSpace definition"}
```

So the intended value is just "application_data", but I didn't want to have a "hardcoded duplicate" of that string in 2 separate locations in the doc (though maybe that's not a real concern and we can just change this to the correct string? or just word it better to make clearer that the value of the struct should be used?)

**Comment by hlandau** [comment]
Yep, I understood that. I just found the use of the CDDL notation a bit surprising here.

**Comment by LPardue** [comment]
I agree with @hlandau here. This seems unique and surprising.

There's several cases in the drafts of fields that have similar crafted types and we just name those types directly when we need to. Lets just use `application_data` here, it's less confusing.
