### ISSUE TITLE
Improve connectivity:connection_id_updated

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#373]
As reported by @hlandau on the mailing list:

connectivity:connection_id_updated

  It would be nice to be able to optionally log CID-associated sequence
  numbers and the type of CID source (ODCID, Initial CID,
  preferred_address transport parameter, NCID frame, etc.)

**Comment by rmarx** [comment]
So, the intent is that this type of information can/should be inferred from other events surrounding the `connection_id_updated` event (e.g., receipt of NCID frames, receipt of an initial from the client, etc.)

While conceptually we can add the fields you want to this event as well, we'd be getting deeper into "everything can be logged in multiple ways" territory (of which we already have too many imo), so I'm personally not the biggest fan.

That said, there's of course an argument that this would be useful for implementations not logging the full set of other events (though I'm not sure how much we want to pander specifically to this use case, as it would need adding other fields to other events as well).

**Comment by hlandau** [comment]
Hmm... so basically you're saying the preferred approach is to note connection IDs from logged NCID frames, etc., then correlate that to connection_id_updated.

I think that's entirely valid, so I'm somewhat retracting this suggestion &mdash; no need to add redundancy here &mdash; unless other people think it's valuable.

**Comment by LPardue** [comment]
Seems like we can close with no action.
