### ISSUE TITLE
Updates for draft-25

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#46]
For now, there's just one I'm aware of:

parameters_set.idle_timeout was renamed to .max_idle_timeout

**Comment by marten-seemann** [comment]
There was also HANDSHAKE_DONE, but we added that already.

**Comment by LPardue** [comment]
maybe this was flagged a while back but `HTTP3EventType:dependency_update`

**Comment by rmarx** [comment]
@LPardue I think that's a specific issue for the TypeScript definitions that's not in the qlog draft itself? I've fixed in for ts here: https://github.com/quiclog/qlog/commit/cf4af5b227289fb32cde9dc9e39ee6a963a08384
