### ISSUE TITLE
Add IP addresses to datagram_* events

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#57]
We currently extracted these to other events, assuming they wouldn't change or only change sparingly at specific times, handled by other events (e.g., when doing migration).

However, this is not always the case. For example, @huitema mentioned:

> NAT rebinding, probes of packets before migration

For these cases, it would be interesting to have (optional) IP from/to addresses in the datagram_* events as well.

**Comment by LPardue** [comment]
If you want to cover migration, you probably want to include the port numbers too

**Comment by lnicco** [comment]
yeah I discussed this with Robin. He recommended considering a `PathInfo` struct that basically contains the 4 tuple and it can be reused for all cases, including Connection Migration and Multi-path

**Comment by rmarx** [comment]
Solved by https://github.com/quicwg/qlog/pull/336
