### ISSUE TITLE
Consider splitting up parameters_set

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#58]
Currently, the parameters related events aggregate all sorts of parameters, doesn't matter where they come from. Good example is transport:parameters_set, which contains mostly data that's transported via TLS (Transport params, alpn), but also some other fields (like QUIC version). 

Some people (@huitema, @marten-seemann) have advocated splitting up this event into others. I personally don't see the benefit of that, so this issue is to track outside arguments and proposed solutions.

**Comment by LPardue** [comment]
One problem with the current design is that it couples QUIC's transport parameters with the handshake. Some of that data is provided by TLS to QUIC, but other things like ALPN are not used by the QUIC transport. 

A more natural model could be a series of handshake events, as suggested by others.

**Comment by rmarx** [comment]
4 years in, I think the combined `parameters_set` approach is pretty fixed and works well enough in practice (and I still don't see much concrete value splitting up), so closing without action.
