### ISSUE TITLE
Allow listing which events were supported by the logger

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#72]
When looking at a qlog at this time, if there is a certain event type missing, you don't know if it's because those events never occurred or if the implementation simply doesn't support/log that event type. 

This is especially troublesome if you want to selectively enable/disable certain types to reduce overhead when you're doing targeted "live" debugging on a deployed system.

The simplest solution I can see is to add a new field to `configuration`, for example:

> supportedEvents:Array\<string\> // each string is category:event_type (e.g., transport:packet_sent)

Some bikeshedding can help to decide if we need two separate fields (supportedCategories separately for example) or if we can cut out the category in here completely (as there is little overlap in event names atm).

This would also be interesting for doing a fast "is this trace compatible with this visualization"-check in qvis and others tools. 

Thanks to @mjoras for reporting.

**Comment by marten-seemann** [comment]
This only captures a subset of the possible changes. For example, you wouldn't be able to tell if a  qlog implementation already supported the recently added `stateless_reset` packet type or not.

In the end, I think it makes more sense to add some kind of versioning scheme to your qlog file (which is orthogonal to the `qlog_version`), and would not be interpreted by tools.

**Comment by rmarx** [comment]
I'm not sure I follow you here...
If the implementation doesn't support stateless_reset, it won't log them either in the first place, so them being absent from the `supportedEvents` list is the same.

This is not really intended to show what an implementation "supports" but more what is has "enabled". The situation is that as a user, you get a random qlog file in front of you, on which you need to do analysis. You're looking for the occurrence of a certain event type, but it isn't there. Is that because the event type wasn't being logged for this log (e.g., mvfst wants to selectively log only -some- of the supported event types to keep overhead down) or because it actually never occurred during the connection (e.g., signalling the bug you're looking for).

Could you expand on the orthogonal versioning scheme? For your example of the `stateless_reset`, that would just be `draft-02` going forward from my viewpoint.

**Comment by LPardue** [comment]
I think this can be resolved as 2 optional lists containing event category+type, or name. One list  declares what events were in scope to be logged, one that declares what events were actually logged.

This would allow for easier scanning of traces to determine if they have events of interest - I.e. speeding up finding 1 in 10,000 connections that fail or bwhave in a certain way

**Comment by LPardue** [comment]
Good point. On one hand I think it could be useful to have a list of the events a particular instance is configured to produce if they happened, whatever we named it. On the other hand, my experience with netlogs is that having a huge list at the top of every file is annoying (the reason they have a list of events is different but the effect is quite similar). 

Such a field seems easy enough to add as a custom extension for vendor needs, or a standard extension as follow on work. Therefore closing with no action seems fine to me.

**Comment by rmarx** [comment]
Closing for now, feel free to re-open if you have strong opinions later @marten-seemann or @mjoras.
