### ISSUE TITLE
Add support for connection migration

### ISSUE THREAD

**Issue by rmarx** [quicwg/qlog#79]
Now that this is a bit more mature, it should be added to draft-02.

Via @marten-seemann:
> So I would assume that would best be modeled using a `path_probed` event (which has ips, ports, CID), and then a `path_confirmed` and a `path_abandoned` event

Somewhat ties into #49 and #78 (and all other connectivity events really...).
Also look into how this is modeled in qlog for multipath by UCL (@mpiraux)

**Comment by LPardue** [comment]
@rmarx was this fixed by https://github.com/quicwg/qlog/pull/336

**Comment by rmarx** [comment]
Indeed, this can be closed :)
